services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["./link-shortener", "--storage=postgres"]
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=shortener
      - DB_PASSWORD=password
      - DB_NAME=shortener_db

volumes:
  postgres_data:
